apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: greeting-operator-permissions
subjects:
- kind: ServiceAccount
  namespace: default 
  name: greeting-operator
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: greeting-operator-role